export const LanguageKey = {
  dashboard: {
    nav: 'dashboard_nav',
    pageTitle: 'dashboard_page',
  },
  user: {
    nav: 'user_nav',
    listPageTitle: 'user_list_page',
    addNewButton: 'user_new_button',
    detailPageTitle: 'user_detail_page',
    tableTitle: 'user_table_title',
    detailTitle: 'user_detail_title',
  },
  server: {
    nav: 'server_nav',
    addNewButton: 'server_new_button',
    connectServerButton: 'connect_server_button',
    listPageTitle: 'server_list_page',
    detailPageTitle: 'server_detail_page',
    detailTitle: 'server_detail_title',
    tableTitle: 'server_table_title',
    generalTab: 'server_general_tab',
    statusTab: 'server_status_tab',
    setupTab: 'server_setup_tab',
    nameItem: 'server_item_name',
    hostItem: 'server_item_host',
    portItem: 'server_item_port',
    userItem: 'server_item_user',
    createdAtItem: 'server_item_created_at',
    passwordItem: 'server_item_password',
    inactiveStatus: 'server_inactive_status',
    activeStatus: 'server_active_status',
    used: 'server_used',
    available: 'server_available',
    ram: 'server_ram',
    room: 'server_room',
    network: 'server_network',
    disk: 'server_disk',
    informationTitle: 'information_title',
  },

  site: {
    nav: 'site_nav',
    listPageTitle: 'site_list_page',
    detailPageTitle: 'site_detail_page',
    tableTitle: 'site_table_title',
    detailTitle: 'site_detail_title',
  },
  product: {
    nav: 'product_nav',
    listPageTitle: 'product_list_page',
    detailPageTitle: 'product_detail_page',
    addNewButton: 'product_new_button',
    tableTitle: 'product_table_title',
    detailTitle: 'product_detail_title',
  },
  blog: {
    nav: 'blog_nav',
    listPageTitle: 'blog_list_page',
    detailPageTitle: 'blog_detail_page',
    addNewButton: 'blog_new_button',
    tableTitle: 'blog_table_title',
    detailTitle: 'blog_detail_title',
  },
  language: {
    nav: 'language_nav',
    listPageTitle: 'language_list_page',
    tableTitle: 'language_table_title',
    detailTitle: 'language_detail_title',
    tab_all: 'language_tab_all_label',
    contentItem: 'language_item_content',
    codeItem: 'language_item_code',
    languageItem: 'language_item_language',
  },
  button: {
    login: 'login_button',
    signup: 'signup_button',
    register: 'register_button',
    logout: 'logout_button',
    submit: 'submit_button',
    cancel: 'cancel_button',
    save: 'save_button',
    delete: 'delete_button',
    update: 'update_button',
    create: 'create_button',
    detail: 'detail_button',
    saveChanges: 'save_changes_button',
    needHelp: 'need_help_button',
  },

  menu: {
    home: 'home_menu',
    profile: 'profile_menu',
    settings: 'settings_menu',
  },

  form: {
    createLabel: 'create_form_label',
    updateLabel: 'update_form_label',
    deleteLabel: 'delete_form_label',
    deleteTitle: 'delete_form_title',
    searchItem: 'search_item',
  },
  signin: {
    title: 'signin_title',
    emailItem: 'signin_item_email',
    passwordItem: 'signin_item_password',
    getStarted: 'get_started',
    noAccount: 'no_account',
    rememberMe: 'remember_me',
    allreadyAccount: 'allready_account',
    forgotPassword: 'forgot_password',
  },
  signup: {
    title: 'signup_title',
    description: 'signup_description',
    usernameItem: 'signup_item_user_name',
    emailItem: 'signup_item_email',
    passwordItem: 'signup_item_password',
    agreeTo: 'agree_to',
    termsOfService: 'terms_of_service',
    privacyPolicy: 'privacy_policy',
  },

  table: {
    filterTitle: 'filter_list_title',
    paginationPerPage: 'pagination_per_page',
    numberSelected: 'table_number_selected',
  },

  notification: {
    title: 'notification_title',
    viewAll: 'notification_view_all',
    new: 'notification_new',
    readAll: 'notification_read_all',
    beforeThat: 'notification_before_that',
    count: 'notification_count',
  },

  notify: {
    changedLanguage: 'notify_changed_language',
    successApiCall: 'notify_success_api_call',
    successGetData: 'notify_success_get_data',
    successPostData: 'notify_success_post_data',
    successUpdate: 'notify_success_update',
    successDelete: 'notify_success_delete',
    errorGeneric: 'notify_error_generic',
    errorNetwork: 'notify_error_network',
    errorServer: 'notify_error_server',
    errorNoResults: 'notify_error_no_results',
    errorInvalidData: 'notify_error_invalid_data',
    errorMissingData: 'notify_error_missing_data',
    errorEmptyResponse: 'notify_error_empty_response',
  },
  common: {
    or: 'or',
    of: 'of',
    and: 'and',
    settingTitle: 'setting_title',
    darkModeTitle: 'dark_mode_title',
    lightModeTitle: 'light_mode_title',
    systemModeTitle: 'system_mode_title',
  },
};
